### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [yujinakayama/atom-auto-update-packages#29]
This package will not be loaded after June 1st without changes. There are a couple deprecations on the latest version of this package:

1. Use ::dispose to cancel subscriptions instead of ::off
2. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see what deprecations are being reported on this package.

See https://github.com/atom/atom/issues/6867 for more info.

**Comment by ypresto** [comment]
@yujinakayama Is this repo not maintained anymore? Need fork?

**Comment by iamstarkov** [comment]
=(
![screen shot 2015-06-05 at 12 43 59](https://cloud.githubusercontent.com/assets/559321/8004503/8e4e4a0c-0b80-11e5-9aaf-f0f322dc4ea9.png)

**Comment by iamstarkov** [comment]
@yujinakayama pls, give somebody (who is initiative enough) permissions to the repo

**Comment by iamstarkov** [comment]
if you are not interested more, let community members to maintain project

**Comment by yujinakayama** [comment]
Fixed in auto-update-packages 1.0.0. (#31)
