### ISSUE TITLE
Deprecate / Merge with wufuC/atom-autoupdate-packages

### ISSUE THREAD

**Issue by ProLoser** [yujinakayama/atom-auto-update-packages#44]
Since this project doesn't appear to be super active, why not _officially_ merge efforts and deprecate/combine with https://github.com/wufuC/atom-autoupdate-packages?

**Comment by AnthonyWC** [comment]
The project you link too also doesn't seem active and has an older last commit; but this project also seem inactive.

**Comment by ProLoser** [comment]
Hah touché
